### ISSUE TITLE
Alpha 3x10e-4 jar doesn't start

### ISSUE THREAD

**Issue by MRebhan** [elytra/Teckle#6]
It crashes on [line 62](https://github.com/elytra/Teckle/blob/master/src/main/java/com/elytradev/concrete/resgen/ConcreteResourcePack.java#L62) because the json files are somehow not in the jar

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Teckle (teckle)
Caused by: java.lang.ExceptionInInitializerError
	at com.elytradev.teckle.client.proxy.ClientProxy.registerRenderers(ClientProxy.java:36)
	at com.elytradev.teckle.common.TeckleMod.onPreInit(TeckleMod.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1906)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:778)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:759)
	at com.elytradev.teckle.repack.concrete.resgen.ConcreteResourcePack.<clinit>(ConcreteResourcePack.java:62)
	... 46 more
```

**Comment by darkevilmac** [comment]
Thats fun, will take a look and wee whats causing this.

**Comment by darkevilmac** [comment]
just guessing but I think shadowjar is moving the concrete packages I have in my project, going to refactor real quick.

**Comment by darkevilmac** [comment]
@MRebhan Can you please give this build a shot and confirm its fixed? https://ci.darkevilmac.com/job/Elytra/job/Teckle/job/master/25/

**Comment by unascribed** [comment]
\>not testing your fixes

**Comment by darkevilmac** [comment]
@unascribed I have I just want to confirm with the person that first reported the issue.

**Comment by unascribed** [comment]
![](https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.makeameme.org%2Fcreated%2Fare-you-sure-a2k88q.jpg&f=1)

**Comment by darkevilmac** [comment]
im at about a 5/7 on the sureness scale

**Comment by darkevilmac** [comment]
Going to mark this as closed and push for now, if the issue still occurs on the version you have then please comment on the issue and I'll reopen.

**Comment by MRebhan** [comment]
That build fixed it. Thanks!
