### ISSUE TITLE
Teckle ripping holes in the fabric of spacetime

### ISSUE THREAD

**Issue by exaskye** [elytra/Teckle#9]
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
        at com.elytradev.teckle.common.worldnetwork.common.WorldNetworkDatabase.getSavedDatabase(WorldNetworkDatabase.java:134) ~[WorldNetworkDatabase.class:?]
        at com.elytradev.teckle.common.worldnetwork.common.WorldNetworkDatabase.getNetworkDB(WorldNetworkDatabase.java:122) ~[WorldNetworkDatabase.class:?]
        at com.elytradev.teckle.common.tile.TileItemTube.func_145839_a(TileItemTube.java:179) ~[TileItemTube.class:?]
        at net.minecraft.tileentity.TileEntity.handleUpdateTag(TileEntity.java:331) ~[asc.class:?]
        at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[bno.class:?]
        at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[gw.class:?]
        at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[gw.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 9 more
```

![image](https://user-images.githubusercontent.com/6185037/28242310-00de8cb2-6976-11e7-9fe5-4531d5665269.png)

(This is interrupting the initial chunk load tile entity reading, and breaking everything. pls fix)

**Comment by darkevilmac** [comment]
Cool
